// src/services/products.mock.ts
import { Product } from "@/types/product";

// 🛒 Mock sản phẩm đa dạng danh mục
export const products: Product[] = [
  {
    id: "p1",
    name: "Tai nghe Bluetooth Chống Ồn Pro",
    slug: "tai-nghe-bluetooth-chong-on-pro",
    price: 1200000,
    salePrice: 899000,
    rating: 5,
    reviewsCount: 125,
    category: "electronics",
    thumbnail: "/images/products/headphones.jpg",
    brand: "Sony",
    stock: 58,
    description: "Chống ồn chủ động, pin 30 giờ, hỗ trợ sạc nhanh.",
  },
  {
    id: "p2",
    name: "Áo Thun Nam Cotton Co Giãn",
    slug: "ao-thun-nam-cotton",
    price: 199000,
    salePrice: 139000,
    rating: 4,
    reviewsCount: 48,
    category: "fashion",
    thumbnail: "/images/products/tshirt.jpg",
    brand: "Routine",
    stock: 200,
    description: "Chất liệu thoáng mát, form chuẩn Trend 2024.",
  },
  {
    id: "p3",
    name: "Robot Hút Bụi Tự Đổ Rác",
    slug: "robot-hut-bui-tu-do-rac",
    price: 8990000,
    salePrice: 7590000,
    rating: 4.5,
    reviewsCount: 234,
    category: "home",
    thumbnail: "/images/products/robot.jpg",
    brand: "Xiaomi",
    stock: 15,
    description: "Lau hút 2in1, tự động quay về dock sạc.",
  },
  {
    id: "p4",
    name: "Kem Chống Nắng SPF50+",
    slug: "kem-chong-nang-spf50",
    price: 299000,
    salePrice: 259000,
    rating: 4,
    reviewsCount: 112,
    category: "beauty",
    thumbnail: "/images/products/sunscreen.jpg",
    brand: "SunCo",
    stock: 300,
    description: "Chống nắng toàn diện, dưỡng ẩm da.",
  },
  {
    id: "p5",
    name: "Bộ Đồ Chơi Xếp Hình Lego Mới",
    slug: "lego-xep-hinh-creative",
    price: 1099000,
    salePrice: 999000,
    rating: 5,
    reviewsCount: 65,
    category: "toys",
    thumbnail: "/images/products/lego.jpg",
    brand: "LEGO",
    stock: 45,
    description: "Phát triển trí tuệ sáng tạo cho trẻ.",
  },
  {
    id: "p6",
    name: "Giày Chạy Bộ Ultra Max",
    slug: "giay-chay-bo-ultra",
    price: 1799000,
    salePrice: 1499000,
    rating: 4,
    reviewsCount: 132,
    category: "sports",
    thumbnail: "/images/products/shoes.jpg",
    brand: "Nike",
    stock: 98,
    description: "Trợ lực hoàn hảo cho mọi bước chạy.",
  },
  {
    id: "p7",
    name: "Bàn Phím Cơ RGB Gaming",
    slug: "ban-phim-co-rgb-gaming",
    price: 1599000,
    salePrice: 1199000,
    rating: 5,
    reviewsCount: 185,
    category: "electronics",
    thumbnail: "/images/products/keyboard.jpg",
    brand: "Keychron",
    stock: 76,
    description: "Switch gõ siêu phê, RGB sống động 16 triệu màu.",
  },
  {
    id: "p8",
    name: "Sáp Vuốt Tóc Nam Giữ Nếp Lâu",
    slug: "sap-vuot-toc-giunep",
    price: 169000,
    salePrice: 129000,
    rating: 4,
    reviewsCount: 51,
    category: "beauty",
    thumbnail: "/images/products/wax.jpg",
    brand: "L’Oreal",
    stock: 140,
    description: "Không bết dính, hương thơm quyến rũ.",
  },
];
